- .cicleci/config.yml
Initial configuration for testing using Circle CI
> ci: Add initial config for circle CI

- .vscode/settings.json
- Cargo.lock
- hcaptcha/Cargo.toml
- hcaptcha/src/hcaptcha_request.rs
Update version and enable "V4" feature
> fix(dependencies): 🐛 Update to UUID v1.0.0

- CHANGES.md
> chore: Prepare for next release 2.2.2

- .circleci/config.yml
- .circleci/success.yml
- .circleci/validation.yml
- CHANGELOG.md
* feat(circleci): add validation.yml configuration file
* fix(config.yml): add circleci/continuation orb to support job continuation
* feat(config.yml): create job to check if last commit was made by a specific bot
* chore(circleci): add success.yml configuration file for CircleCI pipeline
> ci: split script into three and select continuation direct to success if bot

- .circleci/config.yml
- CHANGELOG.md
- hcaptcha/release.toml
* chore(circleci/config.yml): upgrade toolkit version from 0.6.0 to 0.8.3
* fix(hcaptcha/release.toml): modify version search pattern in src/lib.rs file
> fix: modify version search pattern in src/lib.rs file

- .circleci/config.yml
- CHANGELOG.md
* feat(.circleci/config.yml): add bot-check context to toolkit/make_release workflow
* docs(CHANGELOG.md): update logging/tracing section and changes section
> ci: add bot-check context to toolkit/make_release workflow

- CHANGELOG.md
- hcaptcha_derive/Cargo.toml
- hcaptcha_derive/src/lib.rs
refactor(hcaptcha_derive): replace proc-macro-error with proc-macro-error2 in lib.rs
> fix(hcaptcha_derive): update dependencies and correct spacing in Cargo.toml

- .circleci/config.yml
- CHANGELOG.md
- ci: update CircleCI config to adjust build matrix and comment out wasi builds
- ci(circleci): update build names and executor in config.yml
- chore(ci): update cargo target list in CircleCI config
- chore(circleci): remove commented-out build configurations
> ci: update CircleCI config to adjust build matrix and comment out wasi builds

- .circleci/config.yml
- .gitignore
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- hcaptcha/src/hcaptcha_error.rs
- mock-verifier/Cargo.toml
- mock-verifier/src/hcaptcha_integration.rs
- mock-verifier/src/helper.rs
- mock-verifier/src/main.rs
- mock-verifier/src/tc001_blank_sitekey.rs
chore(gitignore): add wip to ignore list
chore(Cargo.lock): update dependencies and add new packages
feat(Cargo.toml): add mock-verifier to workspace and rocket dependency
feat(hcaptcha_error): implement Serialize for Code enum
> feat(circleci): add mock-verifier to build matrix

- .circleci/config.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- hcaptcha/Cargo.toml
- hcaptcha/src/hcaptcha.rs
- hcaptcha/src/hcaptcha_client.rs
- hcaptcha_derive/src/lib.rs
- test-wasm/.github/dependabot.yml
- test-wasm/.gitignore
- test-wasm/Cargo.toml
- test-wasm/README.md
- test-wasm/src/lib.rs
- test-wasm/src/utils.rs
- test-wasm/tests/web.rs
refactor: remove non-wasm32 implementation of impl_hcaptcha function
ci: add wasm-pack installation step to CircleCI config
ci(circleci): add wasm_test job and node orb to CircleCI config
feat(hcaptcha): add wasm32 target support and refactor async trait methods
feat(test-wasm): add hcaptcha integration and async test support
> feat(test-wasm): add hcaptcha integration and async test support

- CHANGELOG.md
- README.md
> docs: update README to add Web Assembly section

- .circleci/config.yml
- CHANGELOG.md
- add release-flag parameter to control release pipeline execution
- update toolkit version to 2.9.1 for improved functionality
- adjust release pipeline conditions to include release-flag check
> 👷 ci(circleci): update pipeline configuration for release handling

- .circleci/config.yml
- CHANGELOG.md
- introduce pcu_verbosity parameter for controlling verbosity in pcu executions
- update workflows to utilize the new verbosity parameter for consistency
> 👷 ci(circleci): add pcu_verbosity parameter to config

- .circleci/config.yml
- CHANGELOG.md
- introduce `when_update_pcu` parameter to control pcu updates in workflow configuration
> 👷 ci(circleci): add condition for updating pcu

- .circleci/github_release.yml
- CHANGELOG.md
- create github_release.yml for automated release with CircleCI
- configure parameters for Rust version, docker tag, and pipelines
- define jobs and workflows for release filtering and execution
> 👷 ci(github): add CircleCI config for GitHub release automation

- .circleci/github_release.yml
- CHANGELOG.md
- add remove_ssh_key parameter to improve workflow security configuration
> 👷 ci(circleci): update github release workflow configuration

- .circleci/github_release.yml
- CHANGELOG.md
- delete unused release filter settings from github_release.yml for simplification
> 👷 ci(circleci): remove release filters from config

- .circleci/config.yml
- CHANGELOG.md
- simplify workflow by removing unnecessary jobs
- adjust job requirements for streamlined process
- improve release configuration for hcaptcha package
> 👷 ci(circleci): update GitHub release workflow

- .circleci/config.yml
- PRLOG.md
- bump toolkit version from 2.13.0 to 2.13.2 for latest features
🔧 chore(ci): remove custom pipeline commands and jobs
- delete `pipeline_by_committer` and `choose_pipeline` commands
- replace `choose_pipeline` job with `toolkit/choose_pipeline` for simplification
> 🔧 chore(ci): update CircleCI toolkit version

- PRLOG.md
- hcaptcha/release-hook.sh
- hcaptcha/release.toml
- hcaptcha_derive/release-hook.sh
- create release-hook.sh for building README and changelog
- concatenate readme sections into README.md
- generate changelog with versioning support
> 📦 build(hcaptcha): add release hook script for README and changelog

- PRLOG.md
- hcaptcha/release.toml
- hcaptcha_derive/release.toml
- add './release-hook.sh' as pre-release hook in hcaptcha/release.toml
- add './release-hook.sh' as pre-release hook in hcaptcha_derive/release.toml
> 🔧 chore(release): add pre-release hook to release.toml

- .circleci/config.yml
- .circleci/github_release.yml
- PRLOG.md
- bump toolkit orb version to 2.13.3 in config.yml
- update toolkit orb version to 2.13.3 in github_release.yml
> 👷 ci(circleci): update circleci toolkit version
